server:
  port: 8085
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          sharedCache:
            # ENABLE_SELECTIVE only apply cache to entity with @Cacheable
            mode: ENABLE_SELECTIVE
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
