server:
  port: 8085
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/learning
    username: Wenyu
    password:
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: Postgres
